@startuml
'https://plantuml.com/sequence-diagram

Main : bulding.callElevator()

Main ..> Building
Building : callElevator()
Building : setStatus()
Building : isAvailableOnFloor(int floor)
Building : setDistance(int floor)

Building ..* Elevator

Elevator : toString()
Elevator : getFloor()
Elevator : setFloor()

@enduml